# =============================================================================
# build-txpplugin-txt - Build Textpattern plugin as a TXT package GitHub action
# =============================================================================
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Metadata:
# @author     Ashley Butcher
# @copyright  Copyright (c) 2024 Alien Internet Services
# @license    https://www.gnu.org/licenses/gpl-3.0.html GNU General Public License version 3
# @version    v1
# @link	      https://github.com/alieninternet/build-txpplugin-txt
# =============================================================================

name: Build and Release Plugin
name: Pack and Release Textpattern Plugin

# This workflow is designed to be reusable by other repositories
on:
  workflow_call:
    inputs:
      folder:
        description: 'Folder to package'
        required: false
        default: '.'
        type: string
      package_version:
        description: 'Version of the package (defaults to version from manifest.json)'
        required: false
        type: string
      dry_run:
        description: 'Skip release upload (for testing)'
        required: false
        default: 'false'
        type: string
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository's code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Fetch the latest release of the packager and its checksum
      - name: Get Latest Packager Release Info
        run: |
          LATEST_RELEASE=$(gh api repos/alieninternet/ais_txpplugin_packager/releases/latest)
          PHAR_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | endswith(".phar")) | .browser_download_url')
          CHECKSUM_URL=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | select(.name | endswith(".sha256sum")) | .browser_download_url')
          echo "PHAR_URL=$PHAR_URL" >> $GITHUB_ENV
          echo "CHECKSUM_URL=$CHECKSUM_URL" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Download the PHAR and its checksum
      - name: Download Packager PHAR and Checksum
        run: |
          curl -L -o ais_txpplugin_packager.phar "$PHAR_URL"
          curl -L -o ais_txpplugin_packager.phar.sha256 "$CHECKSUM_URL"

      # Verify the integrity of the PHAR
      - name: Verify Packager Integrity
        run: |
          sha256sum -c ais_txpplugin_packager.phar.sha256

      # Make the PHAR executable
      - name: Make Packager Executable
        run: chmod +x ais_txpplugin_packager.phar

      # Extract version from manifest.json if not provided
      - name: Determine Package Version
        run: |
          if [ -z "${{ inputs.package_version }}" ]; then
            VERSION=$(jq -r '.version' ${{ inputs.folder }}/manifest.json | sed 's/\./_/g')
          else
            VERSION=${{ inputs.package_version }}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      # Construct expected output filename
      - name: Construct Output Filename
        run: |
          PACKAGE_NAME=$(jq -r '.name' ${{ inputs.folder }}/manifest.json)
          OUTPUT_FILE="${PACKAGE_NAME}_v${VERSION}.txt"
          echo "OUTPUT_FILE=$OUTPUT_FILE" >> $GITHUB_ENV

      # Run the packager over the specified directory
      - name: Run Plugin Packager
        run: |
          ./ais_txpplugin_packager.phar package ${{ inputs.folder }}

      # Calculate SHA256 checksum of the generated plugin file
      - name: Calculate SHA256 Checksum
        run: |
          sha256sum "$OUTPUT_FILE" > plugin_checksum.sha256

      # Get the tag name from the GitHub event
      - name: Get Tag Name
        id: get_tag
        run: echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"

      # Upload the plugin and its checksum to the release (unless dry_run)
      - name: Upload Release Assets
        if: ${{ inputs.dry_run != 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          files: |
            ${{ env.OUTPUT_FILE }}
            plugin_checksum.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
