# =============================================================================
# Simple example workflow using alieninternet/build-txpplugin-txt GitHub action
# =============================================================================
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Metadata:
# @author     Ashley Butcher
# @copyright  Copyright (c) 2025 Alien Internet Services
# @license    https://www.gnu.org/licenses/gpl-3.0.html GNU General Public License version 3
# @version    v1
# @link	      https://github.com/alieninternet/build-txpplugin-txt
# =============================================================================

name: Release Textpattern Plugin Package (text format)

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - name: Check-out repository
        uses: actions/checkout@v4

      # Build the plugin_v.txt package and an sha256sum hash file, and publish it to the release
      # folder: The folder where the plugin source files live, defaults to '.' in this case (the root of the repository)
      # package_filename: When omitted defaults to generating the package filename from the plugin's manifest.json file
      # release_files: When set to true, files will be published to the release triggering the build (default is false)
      - name: Build and release package
        uses: alieninternet/build-txpplugin-txt@v1
        with:
          release_files: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
